// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.CodeAnalysis.Elfie.Model.Structures;
using Microsoft.EntityFrameworkCore;
using StudentsApp.Validations;

namespace StudentsApp.Models;

[Index("Code", Name = "UQ__Students__A25C5AA7EEB2DE90", IsUnique = true)]
public partial class Student
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    [Range(2000, int.MaxValue)]
    [UniqueCode]
    public int Code { get; set; }

    [Required]
    [StringLength(25)]
    [MinLength(3)]
    public string Name { get; set; }
    [Range(2010, 2110)]
    public int Year { get; set; }

    [StringLength(50)]
    [MinLength(3)]
    [RegularExpression(@"^[a-zA-Z]{3,}$",ErrorMessage ="Address must be three or more letters")]
    public string Address { get; set; }

    public bool? IsDeleted { get; set; } = false;

    [Column(TypeName = "date")]
    public DateTime? CreatedAt { get; set; } = DateTime.Now;

    [InverseProperty("Student")]
    public virtual ICollection<StudentSubject> StudentSubjects { get; set; } = new List<StudentSubject>();
}